// Step 9 target server.
//
// RenderFlow's WEBHOOK_CALL executor only accepts https (AGENTS rule 17), so the
// adversarial scenarios need a real TLS endpoint. The certificate is the
// throwaway self-signed pair generated by scripts/step9/make-cert.ps1; the worker
// trusts it through NODE_EXTRA_CA_CERTS, which is set when the worker is
// launched, not here.
//
// This server is a test fixture. It is not part of the product and is never
// imported by app or worker code.

const https = require("node:https");
const fs = require("node:fs");
const path = require("node:path");

const CERT_DIR = path.join(__dirname, "certs");
const PORT = Number(process.env.STEP9_TARGET_PORT || 8443);
const SLOW_MS = Number(process.env.STEP9_SLOW_MS || 1500);
const HANG_MS = Number(process.env.STEP9_HANG_MS || 8000);

/** jobId (the Idempotency-Key the executor sends) -> per-path hit counts. */
const hits = new Map();
/** Completed responses, so a late duplicate is detectable. */
const served = new Map();

function record(jobId, route) {
  if (jobId === undefined) {
    return;
  }
  let byRoute = hits.get(jobId);
  if (byRoute === undefined) {
    byRoute = new Map();
    hits.set(jobId, byRoute);
  }
  byRoute.set(route, (byRoute.get(route) || 0) + 1);
}

const server = https.createServer(
  {
    key: fs.readFileSync(path.join(CERT_DIR, "key.pem")),
    cert: fs.readFileSync(path.join(CERT_DIR, "cert.pem")),
  },
  (req, res) => {
    const route = (req.url || "/").split("?")[0];
    const jobId = req.headers["idempotency-key"];

    let attempt = 1;
    if (jobId !== undefined) {
      const key = `${jobId}::${route}`;
      attempt = (served.get(key) || 0) + 1;
      served.set(key, attempt);
    }
    record(jobId, route);

    // /slow holds the connection open so several jobs are genuinely in flight
    // at once, which is what makes the concurrency cap observable.
    if (route === "/slow") {
      setTimeout(() => {
        res.writeHead(200, { "content-type": "application/json" });
        res.end(JSON.stringify({ ok: true, route, attempt }));
      }, SLOW_MS);
      return;
    }

    // /hang holds the request open long enough to guarantee a worker can be
    // killed while the job is genuinely in flight, then answers 200 so the
    // recovered retry can reach SUCCEEDED.
    if (route === "/hang") {
      setTimeout(() => {
        res.writeHead(200, { "content-type": "application/json" });
        res.end(JSON.stringify({ ok: true, route, attempt }));
      }, HANG_MS);
      return;
    }

    if (route === "/fail") {
      res.writeHead(500, { "content-type": "application/json" });
      res.end(JSON.stringify({ ok: false, route, attempt }));
      return;
    }

    if (route === "/stats") {
      res.writeHead(200, { "content-type": "application/json" });
      res.end(
        JSON.stringify({
          hits: Object.fromEntries(
            [...hits.entries()].map(([id, byRoute]) => [id, Object.fromEntries(byRoute)]),
          ),
        }),
      );
      return;
    }

    if (route === "/reset") {
      hits.clear();
      served.clear();
      res.writeHead(200, { "content-type": "application/json" });
      res.end(JSON.stringify({ ok: true, reset: true }));
      return;
    }

    res.writeHead(200, { "content-type": "application/json" });
    res.end(JSON.stringify({ ok: true, route, attempt }));
  },
);

server.listen(PORT, "127.0.0.1", () => {
  console.log(`STEP9_TARGET_READY port=${PORT} slowMs=${SLOW_MS}`);
});
